server:
  port: 8080   

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: zuul-server
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:28080/auth/realms/spring-cloud-gateway-realm
            user-name-attribute: preferred_username
        registration:
          spring-cloud-gateway-client:
            provider: keycloak
            client-id: spring-cloud-gateway-client
            client-secret: newClientSecretGateway
#            client-secret: c5646e42-75b6-4bb2-a4aa-7c0d5a941130
#            client-authentication-method: basic
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

  cloud:
    gateway:
      default-filters:
      - TokenRelay
      - RemoveRequestHeader=Cookie
      routes:
      - id: hotels-service
        uri: http://127.0.0.1:8082/hotels
        predicates:
        - Path=/hotels/**
        
      - id: gallery-service
        uri: http://127.0.0.1:8100/gallery
        predicates:
        - Path=/gallery/**
        
#ribbon:
#  ReadTimeout: 30000
#  ConnectTimeout: 30000

#hystrix:
#    command:
#        default:
#            execution:
#                isolation:
#                    thread:
#                        timeoutInMilliseconds: 60000   

logging:
  level:
    org:
      springframework:
        cloud.gateway: DEBUG
        http.server.reactive: DEBUG
        web.reactive: DEBUG
